# Generated by Django 5.2.3 on 2025-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('alimentos', 'Alimentos'), ('limpeza', 'Produtos de Limpeza'), ('vestuario', 'Vestuário'), ('bazar', 'Bazar')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_validade', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
